const translations = {
  en: {
    navCore: "Core Review", navTest: "Test Phase", navJournal: "Journal", navAuthor: "Author", navFaq: "FAQ", navSupport: "Support",
    heroTitle: "The story behind<br /><em>the core.</em>",
    latestUpdateLabel: "LATEST DEVELOPMENT UPDATE", latestUpdateStatus: "PHASE 2 / ACTIVE DEVELOPMENT", latestUpdateDate: "19 SEPTEMBER 2026", latestUpdateTitle: "Phase 2: Connecting the Core.", latestUpdateCopy: "The main PLATINUM CORE 777 desktop core is now connected with the existing License Review layer through Supabase. The project is moving from separate working parts toward one controlled ecosystem, while CORE REVIEW enters its controlled test phase.",
    systemMapKicker: "THE MODULAR SYSTEM", systemMapTitle: "Three connected layers. One controlled ecosystem.", systemMapCopy: "Each part has a different responsibility. Together they create the closed loop behind the PLATINUM CORE 777 vision.", systemLayer1Title: "PLATINUM CORE 777", systemLayer1Copy: "The protected main desktop core for Owner operations, licensed companies and synchronized business control.", systemLayer2Title: "PLATINUM CORE LICENSE REVIEW", systemLayer2Copy: "The Master Owner and client-license review layer where controlled business activity and license information are managed.", systemLayer3Title: "CORE REVIEW", systemLayer3Copy: "The human-facing mobile layer for users, approvals, verified visits, reviews, notifications and communication.",
    developmentLogKicker: "LIVE DEVELOPMENT LOG", developmentLogTitle: "From a real business to a connected core.", developmentLogCopy: "The project is being built in public, one verified step at a time. This is the current direction of travel.", log1Label: "FOUNDATION", log1Title: "A real business became the first test.", log1Copy: "The vision began with real pressure, real work and the operational needs of a business in Belgrade.", log2Label: "CORE CONCEPT", log2Title: "The modular idea took shape.", log2Copy: "The project developed from one business tool into a connected operating-system concept for people, companies and licensed workspaces.", log3Label: "CONNECTED LAYERS", log3Title: "The systems began speaking to one another.", log3Copy: "The desktop core, License Review and Core Review are being connected through shared, controlled backend logic.", log4Label: "TEST PHASE", log4Title: "CORE REVIEW is entering controlled testing.", log4Copy: "The mobile layer is prepared for selected testers, with access, roles and feedback handled responsibly.", log5Label: "NEXT DECISION", log5Title: "Turn working parts into reliable releases.", log5Copy: "The next stage is documentation, testing, professional presentation and wider preparation — without pretending the work is finished.",
    faq7Q: "Is CORE REVIEW ready for unrestricted public use?", faq7A: "No. The current release is a controlled test version. Access is limited so that the system, roles, communication and feedback can be reviewed responsibly.", faq8Q: "What does a supporter receive during the test phase?", faq8A: "When access is available, a supporter may receive an access code and installation instructions for the controlled test version. This is not a promise of a finished commercial product.", faq9Q: "How can I request account deletion?", faq9A: "Users can request deletion from the app where available, or contact the project at markoplatinum@icloud.com. The external privacy page explains the process in more detail.", faq10Q: "What information does CORE REVIEW use?", faq10A: "Depending on the feature, CORE REVIEW may use account and profile details, approval information, verified visit information, reviews, notes and notifications needed to provide the service.",
    supportTransparencyLabel: "WHERE SUPPORT GOES", supportTransparencyCopy: "Support is directed toward development time, hosting and backend infrastructure, testing, security, documentation, professional demonstrations and the preparation of reliable public releases.",
    heroCopy: "A public journal about the people, principles and technology behind PLATINUM CORE 777 — why CORE REVIEW exists, who stands behind it, what has been built and how the next chapter can be supported.",
    heroButton: "Read the Core Review story <span>↗</span>", homeButton: "Visit the main site", coreReviewTestEyebrow: "CORE REVIEW / TEST VERSION", coreReviewTestTitle: "The test version is live.", coreReviewTestCopy: "With donor support in an amount you choose, according to your possibilities and wishes, you receive an access code and installation instructions.", coreReviewTestLink: "Read more ↗", heroFact1: "INDEPENDENT PROJECT", heroFact2: "BUILT FROM A REAL BUSINESS", heroFact3: "PUBLICLY ACCOUNTABLE",
    featureLabel: "THE CENTRAL IDEA", featureTitle: "The human connection inside the core.",
    featureBody: "<p>PLATINUM CORE 777 is a modular business operating-system concept designed to connect people, clients, companies and licensed workspaces in one controlled and trusted environment.</p><p>CORE REVIEW is the control and orchestration layer inside that idea. It brings the people, roles, case history, documents, messages, decisions and business activity belonging to one matter into a structured review flow.</p><p>The purpose is practical: reduce scattered information, make responsibility visible, protect sensitive access and give the right people a shared understanding of what is happening.</p><p>It is not an open social network and it is not built around exposing everything to everyone. Connections are limited by role, permission and purpose, so trust can grow from context instead of guesswork.</p>",
    featureQuote: "The goal is not to connect everyone. The goal is to connect the right people, in the right context, with the right level of trust.", principle1Title: "CLARITY", principle1Copy: "Relevant information should be understandable, ordered and connected to the case it belongs to.", principle2Title: "RESPONSIBILITY", principle2Copy: "Every action should have a role, a purpose and a visible place in the review history.", principle3Title: "TRUST", principle3Copy: "Privacy and transparency are balanced through controlled access, not through total exposure.",
    journalLabel: "THE JOURNAL", journalTitle: "Questions worth answering.", journalIntro: "The Journal is the public record of the idea: why it exists, what is being built, who is responsible and how people can take part in the next chapter.",
    article1Title: "Why trust begins with the person behind the system", article1Copy: "There is no anonymous corporation behind the story. There is an author, a founder and a CEO publicly standing behind the work.", readArticle: "Read the story ↗",
    article2Title: "Why PLATINUM CORE 777 exists", article2Copy: "A real business created the pressure. A bigger operating-system idea grew from it and is now being developed step by step.",
    article3Title: "Controlled connections, not uncontrolled exposure", article3Copy: "Permissions, roles and traceable activity make connection useful without making everything public or careless.",
    article4Title: "What has been built so far", article4Copy: "The project is in active development. This Journal records the direction, prototypes, lessons and next decisions honestly.", article5Title: "Who is Marko Ćuća and why is he building this?", article5Copy: "The personal story behind the project, the pressure that started it and the responsibility of building something in public.", article6Title: "Why support the next chapter?", article6Copy: "Support helps turn an independently built idea into a tested, documented and more useful system for real businesses and people.", readMore: "Explore the story ↗",
    accountabilityLabel: "AUTHOR & ACCOUNTABILITY", accountabilityTitle: "Built by a person, not a faceless data machine.",
    accountabilityBody: "<p><strong>Author, Founder &amp; CEO of PLATINUM CORE 777 &amp; CORE REVIEW</strong></p><p>PLATINUM CORE 777 is an independent project created by Marko Ćuća from Belgrade. It began with the pressure of a real business, real operational problems and the need to find a clearer way to organize people, work and responsibility.</p><p>The project is not presented as the work of a large anonymous corporation. The author is visible, reachable and publicly connected to the idea, the development process, the mistakes and the decisions made along the way.</p><p>Public documents, releases and statements are signed with the author's verified electronic identity key whenever applicable. That is part of the principle: people should be able to see who stands behind the work and how seriously that responsibility is taken.</p><p>The author does not claim that the project is perfect. He claims responsibility for being transparent, correcting mistakes and continuing to improve the system honestly.</p>",
    faq1Q: "Is this a finished product?", faq1A: "No. PLATINUM CORE 777 is in active development. The Journal makes the direction, progress and limitations visible.",
    faq2Q: "What is CORE REVIEW?", faq2A: "CORE REVIEW is the control and orchestration module that connects people, roles, cases, documents, messages and evidence into a verifiable review flow.",
    faq3Q: "Why are some technical details private?", faq3A: "The public story explains the purpose and principles. Sensitive architecture, code and security details are shared only when it is responsible to do so.",
    faq4Q: "How can someone help?", faq4A: "People can share the story, offer technical or strategic support, suggest a pilot, contact the author or support the next stage of development.",
    faq5Q: "Where does support go?", faq5A: "Support is intended for development time, testing, documentation, professional presentation materials, infrastructure and the practical work required to move the project from prototypes toward reliable releases.",
    faq6Q: "Are the project images and examples real?", faq6A: "The project story is based on real work and a real business. Some early presentation images are AI visualisations used to communicate the idea while resources for professional production are still being built.",
    supportLabel: "THE NEXT CHAPTER", supportTitle: "Help build the future of business.", supportCopy: "If this idea speaks to you, support does not have to mean only money. It can be a conversation, a useful introduction, a pilot opportunity, technical knowledge, strategic advice or help sharing the story with the right people.", supportPoint1Title: "DEVELOPMENT", supportPoint1Copy: "Help move the software from working prototypes toward stable, documented releases.", supportPoint2Title: "PRESENTATION", supportPoint2Copy: "Help create professional videos, demonstrations and materials that explain the story clearly.", supportPoint3Title: "CONNECTIONS", supportPoint3Copy: "Help connect the project with businesses, advisors and people who can test the idea responsibly.", supportButton: "Support the Project ↗", footerLine: "From Belgrade to the World."
  },
  sr: {
    navCore: "Core Review", navTest: "Test Faza", navJournal: "Journal", navAuthor: "Autor", navFaq: "Pitanja", navSupport: "Podrška",
    heroTitle: "Prica iza<br /><em>jezgra.</em>",
    latestUpdateLabel: "NAJNOVIJE O RAZVOJU", latestUpdateStatus: "FAZA 2 / AKTIVAN RAZVOJ", latestUpdateDate: "19. SEPTEMBAR 2026.", latestUpdateTitle: "Faza 2: Povezivanje jezgra.", latestUpdateCopy: "Glavno desktop jezgro PLATINUM CORE 777 sada je povezano sa postojecim License Review slojem kroz Supabase. Projekat prelazi iz odvojenih radnih delova u kontrolisan ekosistem, dok CORE REVIEW ulazi u kontrolisanu test fazu.",
    systemMapKicker: "MODULARNI SISTEM", systemMapTitle: "Tri povezana sloja. Jedan kontrolisan ekosistem.", systemMapCopy: "Svaki deo ima drugu odgovornost. Zajedno stvaraju zatvorenu vezu iza vizije PLATINUM CORE 777.", systemLayer1Title: "PLATINUM CORE 777", systemLayer1Copy: "Zasticeno glavno desktop jezgro za Owner rad, licencirane firme i sinhronizovanu kontrolu poslovanja.", systemLayer2Title: "PLATINUM CORE LICENSE REVIEW", systemLayer2Copy: "Master Owner i client-license sloj za kontrolisan pregled poslovnih aktivnosti i podataka o licencama.", systemLayer3Title: "CORE REVIEW", systemLayer3Copy: "Mobilni sloj okrenut ljudima za korisnike, odobrenja, verifikovane posete, ocene, obavestenja i komunikaciju.",
    developmentLogKicker: "JAVNI RAZVOJNI DNEVNIK", developmentLogTitle: "Od stvarnog biznisa do povezanog jezgra.", developmentLogCopy: "Projekat se gradi javno, korak po korak. Ovo je trenutni pravac razvoja.", log1Label: "TEMELJ", log1Title: "Stvarni biznis postao je prvi test.", log1Copy: "Vizija je pocela iz stvarnog pritiska, stvarnog rada i operativnih potreba biznisa u Beogradu.", log2Label: "CORE IDEJA", log2Title: "Modularna ideja dobila je oblik.", log2Copy: "Projekat je od jednog poslovnog alata prerastao u povezani operativni sistem za ljude, firme i licencirane radne prostore.", log3Label: "POVEZANI SLOJEVI", log3Title: "Sistemi su poceli da rade zajedno.", log3Copy: "Desktop jezgro, License Review i Core Review povezuju se kroz zajednicku i kontrolisanu backend logiku.", log4Label: "TEST FAZA", log4Title: "CORE REVIEW ulazi u kontrolisano testiranje.", log4Copy: "Mobilni sloj je pripremljen za odabrane testere, uz odgovorno upravljanje pristupom, ulogama i povratnim informacijama.", log5Label: "SLEDECA ODLUKA", log5Title: "Pretvoriti radne delove u pouzdana izdanja.", log5Copy: "Sledeci korak su dokumentacija, testiranje, profesionalna prezentacija i priprema za siri rad — bez pretvaranja da je posao zavrsen.",
    faq7Q: "Da li je CORE REVIEW spreman za potpuno javno koriscenje?", faq7A: "Ne. Trenutno izdanje je kontrolisana test verzija. Pristup je ogranicen kako bi se sistem, uloge, komunikacija i povratne informacije odgovorno proverili.", faq8Q: "Sta podrzalac dobija tokom test faze?", faq8A: "Kada je pristup dostupan, podrzalac moze dobiti pristupni kod i instrukcije za instalaciju kontrolisane test verzije. To nije obecanje zavrsenog komercijalnog proizvoda.", faq9Q: "Kako mogu da zatrazim brisanje naloga?", faq9A: "Korisnik moze zatraziti brisanje iz aplikacije kada je opcija dostupna ili kontaktirati projekat na markoplatinum@icloud.com. Spoljna stranica privatnosti objasnjava proces.", faq10Q: "Koje informacije CORE REVIEW koristi?", faq10A: "U zavisnosti od funkcije, CORE REVIEW moze koristiti podatke naloga i profila, podatke o odobrenju, verifikovanoj poseti, ocenama, beleskama i obavestenjima potrebnim za rad usluge.",
    supportTransparencyLabel: "GDE IDE PODRSKA", supportTransparencyCopy: "Podrska je namenjena vremenu za razvoj, hostingu i backend infrastrukturi, testiranju, bezbednosti, dokumentaciji, profesionalnim demonstracijama i pripremi pouzdanih javnih izdanja.",
    heroCopy: "Javni Journal o ljudima, principima i tehnologiji iza projekta PLATINUM CORE 777 — zašto CORE REVIEW postoji, ko stoji iza njega, šta je izgrađeno i kako može da se podrži sledeća faza.",
    heroButton: "Pročitaj priču o Core Review-u <span>↗</span>", homeButton: "Glavni sajt", coreReviewTestEyebrow: "CORE REVIEW / TESTNA VERZIJA", coreReviewTestTitle: "Testna verzija je objavljena.", coreReviewTestCopy: "Uz donatorsku podršku u iznosu koji sami odredite, u skladu sa svojim mogućnostima i željama, dobijate pristupni kod i instrukcije za instalaciju.", coreReviewTestLink: "Pročitaj više ↗", heroFact1: "NEZAVISAN PROJEKAT", heroFact2: "NASTAO IZ STVARNOG BIZNISA", heroFact3: "JAVNA ODGOVORNOST",
    featureLabel: "CENTRALNA IDEJA", featureTitle: "Ljudska veza unutar jezgra.",
    featureBody: "<p>PLATINUM CORE 777 je modularni koncept poslovnog operativnog sistema, osmišljen da poveže ljude, klijente, firme i licencirane radne prostore u jednom kontrolisanom i pouzdanom okruženju.</p><p>CORE REVIEW je kontrolni i koordinacioni sloj te ideje. On objedinjuje ljude, uloge, istoriju slučaja, dokumente, poruke, odluke i poslovne aktivnosti koje pripadaju jednom predmetu u strukturisan tok pregleda.</p><p>Svrha je praktična: manje rasutih informacija, jasnija odgovornost, zaštićen pristup osetljivim podacima i zajedničko razumevanje onoga što se dešava.</p><p>To nije otvorena društvena mreža i nije zasnovano na tome da svi vide sve. Povezivanje je ograničeno ulogom, dozvolom i svrhom, kako bi poverenje nastajalo iz konteksta, a ne iz pretpostavki.</p>",
    featureQuote: "Cilj nije da poveže sve ljude. Cilj je da poveže prave ljude, u pravom kontekstu, sa pravim nivoom poverenja.", principle1Title: "JASNOĆA", principle1Copy: "Važne informacije treba da budu razumljive, uređene i povezane sa slučajem kojem pripadaju.", principle2Title: "ODGOVORNOST", principle2Copy: "Svaka aktivnost treba da ima ulogu, svrhu i vidljivo mesto u istoriji pregleda.", principle3Title: "POVERENJE", principle3Copy: "Privatnost i transparentnost usklađuju se kontrolisanim pristupom, a ne potpunim izlaganjem.",
    journalLabel: "JOURNAL", journalTitle: "Pitanja na koja vredi odgovoriti.", journalIntro: "Journal je javni zapis ideje: zašto postoji, šta se gradi, ko je odgovoran i kako ljudi mogu da učestvuju u sledećoj fazi.",
    article1Title: "Zasto poverenje pocinje od osobe iza sistema", article1Copy: "Iza price ne stoji anonimna korporacija. Iza nje stoji autor, osnivac i CEO koji javno stoji iza rada.", readArticle: "Procitaj pricu ↗",
    article2Title: "Zašto postoji PLATINUM CORE 777", article2Copy: "Jedan stvarni posao stvorio je pritisak. Iz njega je izrasla veća ideja poslovnog operativnog sistema koja se sada razvija korak po korak.",
    article3Title: "Kontrolisane veze, a ne nekontrolisano izlaganje", article3Copy: "Dozvole, uloge i proverljive aktivnosti omogućavaju povezivanje bez toga da sve postane javno ili neodgovorno.",
    article4Title: "Šta je do sada izgrađeno", article4Copy: "Projekat je u aktivnom razvoju. Journal iskreno beleži pravac, prototipe, naučene lekcije i sledeće odluke.", article5Title: "Ko je Marko Ćuća i zašto ovo gradi?", article5Copy: "Lična priča iza projekta, pritisak iz kojeg je nastao i odgovornost izgradnje nečega pred javnošću.", article6Title: "Zašto podržati sledeću fazu?", article6Copy: "Podrška pomaže da nezavisno izgrađena ideja postane testiran, dokumentovan i korisniji sistem za stvarne firme i ljude.", readMore: "Istraži priču ↗",
    accountabilityLabel: "AUTOR I ODGOVORNOST", accountabilityTitle: "Pravi ga covek, a ne bezlicna masina za podatke.",
    accountabilityBody: "<p><strong>Author, Founder &amp; CEO of PLATINUM CORE 777 &amp; CORE REVIEW</strong></p><p>PLATINUM CORE 777 je nezavisan projekat Marka Ćuće iz Beograda. Nastao je pod pritiskom stvarnog biznisa, stvarnih operativnih problema i potrebe da se jasnije organizuju ljudi, rad i odgovornost.</p><p>Projekat se ne predstavlja kao rad velike anonimne korporacije. Autor je vidljiv, dostupan i javno povezan sa idejom, razvojem, greškama i odlukama koje se donose.</p><p>Javni dokumenti, izdanja i izjave potpisuju se verifikovanim elektronskim ključem autora kada je to primenljivo. To je deo principa: ljudi treba da vide ko stoji iza rada i koliko se ta odgovornost ozbiljno shvata.</p><p>Autor ne tvrdi da je projekat savršen. Preuzima odgovornost za transparentnost, ispravke i pošten nastavak razvoja.</p>",
    faq1Q: "Da li je ovo zavrsen proizvod?", faq1A: "Ne. PLATINUM CORE 777 je u aktivnom razvoju. Journal otvoreno prikazuje pravac, napredak i ogranicenja.",
    faq2Q: "Sta je CORE REVIEW?", faq2A: "CORE REVIEW je kontrolni i koordinacioni modul koji povezuje ljude, uloge, slucajeve, dokumente, poruke i dokaze u proverljiv tok.",
    faq3Q: "Zasto su neki tehnicki detalji privatni?", faq3A: "Javna prica objasnjava svrhu i principe. Osetljiva arhitektura, kod i bezbednosni detalji dele se samo kada je to odgovorno.",
    faq4Q: "Kako neko može da pomogne?", faq4A: "Deljenjem priče, tehničkom ili strateškom podrškom, predlogom za pilot, kontaktom sa autorom ili podrškom sledećoj fazi razvoja.",
    faq5Q: "Gde odlazi podrška?", faq5A: "Podrška je namenjena vremenu za razvoj, testiranju, dokumentaciji, profesionalnim prezentacionim materijalima, infrastrukturi i praktičnom radu potrebnom da prototipi postanu pouzdana izdanja.",
    faq6Q: "Da li su slike i primeri projekta stvarni?", faq6A: "Priča projekta zasnovana je na stvarnom radu i stvarnom biznisu. Neke početne prezentacione slike su AI vizuelizacije koje pomažu da se ideja predstavi dok se ne obezbede sredstva za profesionalnu produkciju.",
    supportLabel: "SLEDEĆA FAZA", supportTitle: "Pomozite da izgradimo budućnost poslovanja.", supportCopy: "Ako vam ova ideja znači, podrška ne mora da bude samo novac. To može biti razgovor, koristan kontakt, prilika za pilot, tehničko znanje, strateški savet ili pomoć da priča dođe do pravih ljudi.", supportPoint1Title: "RAZVOJ", supportPoint1Copy: "Pomozite da se softver iz funkcionalnih prototipa pretvori u stabilna i dokumentovana izdanja.", supportPoint2Title: "PREZENTACIJA", supportPoint2Copy: "Pomozite u stvaranju profesionalnih videa, demonstracija i materijala koji jasno objašnjavaju priču.", supportPoint3Title: "POVEZIVANJE", supportPoint3Copy: "Povežite projekat sa firmama, savetnicima i ljudima koji mogu odgovorno da testiraju ideju.", supportButton: "Podrži projekat ↗", footerLine: "Od Beograda ka svetu."
  }
};

const setLanguage = (language) => {
  const copy = translations[language] || translations.en;
  document.documentElement.lang = language === "sr" ? "sr" : "en";
  document.querySelectorAll("[data-i18n]").forEach((node) => {
    const value = copy[node.dataset.i18n];
    if (value !== undefined) node.innerHTML = value;
  });
  document.querySelectorAll("[data-i18n-html]").forEach((node) => {
    const value = copy[node.dataset.i18nHtml];
    if (value !== undefined) node.innerHTML = value;
  });
  document.querySelectorAll(".lang").forEach((button) => {
    const active = button.dataset.language === language;
    button.classList.toggle("is-active", active);
    button.setAttribute("aria-pressed", String(active));
  });
  window.localStorage.setItem("pc777-journal-language", language);
};

document.querySelectorAll(".lang").forEach((button) => {
  button.addEventListener("click", () => setLanguage(button.dataset.language));
});

setLanguage(window.localStorage.getItem("pc777-journal-language") || "en");
